# its contents configure the TGIS server & caikit
jvm_options: []

runtime:
  batching:
    standalone-model:
      size: 0 # Set to batch size for batching
  server_thread_pool_size: 16

inference_plugin:
  model_mesh:
    max_loading_concurrency: 1
    latency_based_autoscaling_enabled: false

module_backends:
  load_priority:
    - type: TGIS
      config:
        local:
          load_timeout: 120
          grpc_port: null
          http_port: null
          health_poll_delay: 1.0
        connection:
          hostname: "TGIS_HOSTNAME"
          ca_cert_file: null
          client_cert_file: null
          client_key_file: null
